import Head from 'next/head';
import AdminLayout from '../../../components/layouts/adminLayout';
import { NextPageWithLayout } from '../../_app';

const ProductionsPage: NextPageWithLayout = () => {

  return (
    <div dir='rtl'>
      <Head>
        <title>فروشگاه زنجیره ای - ادمین - محصولات</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Productions</div>
    </div>
  )
}

ProductionsPage.getLayout = (page) => (<AdminLayout>{page}</AdminLayout>);
export default ProductionsPage;
