import { useEffect } from 'react';
import Head from 'next/head'
import Login from '../../components/authentication/login'
import { motion } from 'framer-motion';
import { useAppSelector } from '../../app/hooks';
import { RootState } from '../../app/store';
import { useRouter } from 'next/router';
import { NextPageWithLayout } from '../_app';
import GuestLayout from '../../components/layouts/guestLayout';

const LoginPage: NextPageWithLayout = () => {

  const token = useAppSelector((state: RootState) => state.auth.verifyToken);
  const rooter = useRouter();

  useEffect(() => {
    if (token) rooter.push('/');

  },[token]);

  return (
    <div dir='rtl' >
      <Head>
        <title>Create Next App - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0, x: -900 }}
        animate={{
          opacity: 1, x: 0, transition: {
            duration: 0.8,
          },
        }}
      >
        <Login />
      </motion.div>

    </div>
  )
}
LoginPage.getLayout = (page) => (<GuestLayout>{page}</GuestLayout>);

export default LoginPage