import type { NextPage } from 'next'
import Head from 'next/head'
import Login from '../../components/authentication/login'
import { motion } from 'framer-motion';
import { useAppSelector } from '../../app/hooks';
import { RootState } from '../../app/store';
import { useRouter } from 'next/router';

const LoginPage: NextPage = () => {

  const token = useAppSelector((state: RootState) => state.auth.verifyToken);
  const rooter = useRouter();
  if (token) rooter.push('/');


  return (
    <div dir='rtl' >
      <Head>
        <title>Create Next App - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0, y: -300 }}
        animate={{
          opacity: 1, y: 0, transition: {
            duration: 0.8,
          },
        }}
      >
        <Login />
      </motion.div>

    </div>
  )
}

export default LoginPage