import { useEffect } from 'react';
import Head from 'next/head'
import Register from '../../components/authentication/register'
import { motion } from 'framer-motion';
import { useAppSelector } from '../../app/hooks';
import { useRouter } from 'next/router';
import { RootState } from '../../app/store';
import GuestLayout from '../../components/layouts/guestLayout';
import { NextPageWithLayout } from '../_app';

const RegisterPage: NextPageWithLayout = () => {

  const token = useAppSelector((state: RootState) => state.auth.verifyToken);
  const rooter = useRouter();

  useEffect(() => {
    if (token) rooter.push('/');

  },[token]);

  return (
    <div dir='rtl' >
      <Head>
        <title>Create Next App - Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0, x: -900 }}
        animate={{
          opacity: 1,x: 0, transition: {
            duration: 0.8,
          
          },
        }}
      >
        <Register />
      </motion.div>

    </div>
  )
}
RegisterPage.getLayout = (page) => (<GuestLayout>{page}</GuestLayout>);

export default RegisterPage