import type { NextPage } from 'next'
import Head from 'next/head'
import Register from '../../components/authentication/register'
import { motion } from 'framer-motion';
import { useAppSelector } from '../../app/hooks';
import { useRouter } from 'next/router';
import { RootState } from '../../app/store';

const RegisterPage: NextPage = () => {


  const token = useAppSelector((state: RootState) => state.auth.verifyToken);
  const rooter = useRouter();
  if (token) rooter.push('/');


  return (
    <div dir='rtl' >
      <Head>
        <title>Create Next App - Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0, y: -300 }}
        animate={{
          opacity: 1, y: 0, transition: {
            duration: 0.8,
          
          },
        }}
      >
        <Register />
      </motion.div>

    </div>
  )
}

export default RegisterPage