import Head from 'next/head';
import Router from 'next/router';
import { useAppSelector } from '../../app/hooks';
import UserLayout from '../../components/layouts/userLayout';

import { NextPageWithLayout } from '../_app';
import Products from '../../components/navbar/neccessaryItems/purchasePreview/products';


const CartPage: NextPageWithLayout = () => {

  // const token = useAppSelector((state) => state.auth.verifyToken)
  // if (!token) {
  //   Router.push('/');
  //   return <></>
  // }
  
  return (
    <div dir='rtl'>
      <Head>
        <title>فروشگاه زنجیره ای - پنل</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Products/>
      </div>
    </div>
  )
}

CartPage.getLayout = (page) => (<UserLayout>{page}</UserLayout>);
export default CartPage