import Head from 'next/head';
import Link from 'next/link';
import React from 'react'

const NotFound: React.FC = () => {

    return (
        <div>
            <Head>
                <title>فروشگاه زنجیره ای - 404</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="h-screen w-full flex flex-col justify-center items-center bg-[#1A2238]">
                <h1 className="text-9xl font-extrabold text-white tracking-widest">404</h1>
                <div className="bg-[#FF6A3D] px-2 text-sm rounded rotate-12 absolute">صفحه ای پیدا نشد</div>
                <button className="mt-5">
                    <div className="relative inline-block text-sm font-medium text-[#FF6A3D] group active:text-orange-500 focus:outline-none focus:ring">
                        <span className="absolute inset-0 transition-transform translate-x-0.5 translate-y-0.5 bg-[#FF6A3D] group-hover:translate-y-0 group-hover:translate-x-0">
                        </span>
                        <span className="relative block px-8 py-3 bg-[#1A2238] border border-current">
                            <Link href='/'><a>برو به صفحه اصلی</a></Link>
                        </span>
                    </div>
                </button>
            </main>
        </div>
    )
}

export default NotFound;
