import Head from 'next/head';
import AdminLayout from '../components/layouts/adminLayout';
import { NextPageWithLayout } from './_app';

const AdminPage: NextPageWithLayout = () => {

  return (
    <div dir='rtl'>
      <Head>
        <title>فروشگاه زنجیره ای - پنل</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        AdminPage
      </div>
    </div>
  )
}

AdminPage.getLayout = (page) => (<AdminLayout>{page}</AdminLayout>);
export default AdminPage;
