import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Navbar from '../components/navbar';
import Menu from '../components/menu';
import Slider from '../components/slider';
import { motion } from 'framer-motion';

const Home: NextPage = () => {
  return (
    <div dir='rtl'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        
        initial={{ opacity: 0 }}
        animate={{ opacity: 1,
          transition: {
            duration: 0.8,
          
          }, }}
      >
      <Navbar />
      <Menu />
      <Slider/>
      <footer className={styles.footer}><Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /></footer>
      </motion.div>
    </div>
  )
}

export default Home
