import Head from 'next/head';
import Home from './../components/home';
import { axiosAPI } from '../app/lib/api';
import { useAppDispatch } from '../app/hooks';
import { setProducts } from '../app/store/productsSlice';
import { NextPageWithLayout } from './_app';
import GuestLayout from '../components/layouts/guestLayout';
import { useEffect } from 'react';

interface Props { props: { data: any } }

const HomePage: NextPageWithLayout<Props> = ({ props }) => {

  const dispatch = useAppDispatch();

  useEffect(()=>{
    dispatch(setProducts(props.data));

  })

  return (
    <div>
      <Head>
        <title>فروشگاه زنجیره ای</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  )
}
HomePage.getLayout = (page) => (<GuestLayout>{page}</GuestLayout>);
HomePage.getInitialProps = async () => {

  const { data } = await axiosAPI("/products", "get", { populate: "*" });

  return { props: { data, }, }
}

export default HomePage;




