import Head from 'next/head';
import Home from './../components/home';
import { motion } from 'framer-motion';
import { InferGetServerSidePropsType,GetServerSideProps } from 'next';
import { axiosAPI } from '../app/lib/api';
import { useAppDispatch } from '../app/hooks';
import { setProducts } from '../app/store/productsSlice';

const HomePage = ({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) => {


  const dispatch = useAppDispatch();
  dispatch(setProducts(data));

  return (
    <div dir='rtl'>
      <Head>
        <title>فروشگاه زنجیره ای</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1, transition: { duration: 0.8, }, }}>
        <Home />
      </motion.div>
    </div>
  )
}

export default HomePage;

export const getServerSideProps: GetServerSideProps<{ data: any }> = async () => {

  const { data } = await axiosAPI("/products", "get", { populate: "*" });

  return { props: { data, }, }

}





