import Head from 'next/head';
import Router from 'next/router';
import { useAppSelector } from '../app/hooks';
import UserLayout from '../components/layouts/userLayout';


import Panel from './../components/panel'
import { NextPageWithLayout } from './_app';

const PanelPage: NextPageWithLayout = () => {

  // const token = useAppSelector((state) => state.auth.verifyToken)
  // if (!token) {
  //   Router.push('/');
  //   return <></>
  // }
  
  return (
    <div dir='rtl'>
      <Head>
        <title>فروشگاه زنجیره ای - پنل</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Panel />
    </div>
  )
}

PanelPage.getLayout = (page) => (<UserLayout>{page}</UserLayout>);
export default PanelPage
