import type { NextPage } from 'next';
import Head from 'next/head';
import Panel from './../components/panel'

const HomePage: NextPage = () => {
  return (
    <div dir='rtl'>
      <Head>
        <title>فروشگاه زنجیره ای - پنل</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Panel/>
    </div>
  )
}

export default HomePage
