import type { NextPage } from 'next'
import Head from 'next/head'
import Register from '../components/authentication/register'


const Home: NextPage = () => {
  return (
    <div dir='rtl'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Register/>
    </div>
  )
}

export default Home