import type { NextPage } from 'next'
import Head from 'next/head'
import Register from '../components/authentication/register'
import { motion } from 'framer-motion';

const Home: NextPage = () => {
  return (
    <div dir='rtl' >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
      >
        <Register />
      </motion.div>
  
    </div>
  )
}

export default Home