import type { Metadata } from "next";
import "./../styles/globals.css";

export const metadata: Metadata = {
  title: "فروشگاه زنجیره ای",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={``}
      >
        {children}
      </body>
    </html>
  );
}
