import Head from 'next/head';
import Users from '../../../components/admin/users';
import AdminLayout from '../../../components/layouts/adminLayout';
import { NextPageWithLayout } from '../../_app';

const UsersPage: NextPageWithLayout = () => {

  return (
    <div dir='rtl'>
      <Head>
        <title>فروشگاه زنجیره ای - ادمین - کاربران</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Users/>
    </div>
  )
}

UsersPage.getLayout = (page) => (<AdminLayout>{page}</AdminLayout>);
export default UsersPage;
