import Head from 'next/head';
import { axiosAPI } from '../../app/lib/api';
import { useRouter } from 'next/router';
import { NextPageWithLayout } from '../_app';
import GuestLayout from '../../components/layouts/guestLayout';
import DetailsProducts from '../../components/home/products/detailsProducts';

const DetailsProductsPage: NextPageWithLayout = ({ props }: any) => {

  const { data, slug } = props;
  const rooter = useRouter();

  const product = data.find((item: any) => (item.attributes.slug === slug));

  if (!product) {
    // go to 404 page
    rooter.push('/404');
  }

  return (
    <div dir='rtl'>
      <Head>
        <title>جزئیات محصول {slug}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {product && <DetailsProducts item={product} />}
    </div>
  )
}
DetailsProductsPage.getLayout = (page) => (<GuestLayout>{page}</GuestLayout>);
DetailsProductsPage.getInitialProps = async (params: any) => {

  const { slug } = params.query;
  const { data } = await axiosAPI(`/products`, "get", { populate: "*", filters: { slug } });
  return { props: { data, slug } }
}

export default DetailsProductsPage;


