import Head from 'next/head';
import { motion } from 'framer-motion';
import DetailsProducts from '../../components/products/detailsProducts';
import { InferGetServerSidePropsType, GetServerSideProps, NextPage } from 'next';
import { axiosAPI } from '../../app/lib/api';
import { useRouter } from 'next/router';

type GetServer = InferGetServerSidePropsType<typeof getServerSideProps>;

const HomePage: NextPage<GetServer> = ({ data, slug }: GetServer) => {

  const rooter = useRouter();

  const product = data.find((item: any) => (item.attributes.slug === slug));

  if (!product) {
    // go to 404 page
    rooter.push('/404');
  }

  return (
    <div dir='rtl'>
      <Head>
        <title>جزئیات محصول {slug}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1, transition: { duration: 0.8, }, }}>
        {product && <DetailsProducts item={product} />}
      </motion.div>
    </div>
  )
}

export default HomePage

export const getServerSideProps: GetServerSideProps<{ data: any, slug: string }> = async ({ params }) => {

  const { slug } = params as any;
  // console.log(slug)
  const { data } = await axiosAPI(`/products`, "get", { populate: "*", filters: { slug } });
  return { props: { data, slug } }

}
