import type { NextPage } from 'next';
import Head from 'next/head';

import { motion } from 'framer-motion';
import { useRouter } from 'next/router';
import DetailsProducts from '../../components/products/detailsProducts';
import Products from '../../components/products/products.json';
import Product from '../../components/models/Product';

const HomePage: NextPage = () => {

  const router = useRouter();
  const { slug } = router.query
  const product: Product = Products.find(item => (item.slug === slug)) as Product;

  return (
    <div dir='rtl'>
      <Head>
        <title>جزئیات محصول {slug}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1, transition: { duration: 0.8, }, }}>
        <DetailsProducts item={product} />
      </motion.div>
    </div>
  )
}

export default HomePage